"""
MACH-1 Database
SQLite database with 9 tables and indexes.
All data lives here — portable, single file.
"""
import sqlite3
import json
from datetime import datetime, timezone
from pathlib import Path
from contextlib import contextmanager
from typing import Optional

from config import DB_PATH
from utils.logger import get_logger

log = get_logger("mach1.db")

SCHEMA = """
-- ═══ 1. RSS Sources ═══
CREATE TABLE IF NOT EXISTS rss_sources (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL,
    url         TEXT NOT NULL UNIQUE,
    category    TEXT DEFAULT 'general',
    enabled     INTEGER DEFAULT 1,
    last_fetched TEXT,
    created_at  TEXT DEFAULT (datetime('now'))
);

-- ═══ 2. Topics (scraped from RSS) ═══
CREATE TABLE IF NOT EXISTS topics (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title       TEXT NOT NULL,
    url         TEXT UNIQUE,
    source_id   INTEGER REFERENCES rss_sources(id),
    summary     TEXT,
    score       REAL DEFAULT 0.0,
    status      TEXT DEFAULT 'new' CHECK(status IN ('new','ranked','selected','used','rejected')),
    created_at  TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_topics_status ON topics(status);
CREATE INDEX IF NOT EXISTS idx_topics_score ON topics(score DESC);

-- ═══ 3. Content Items (generated by content team) ═══
CREATE TABLE IF NOT EXISTS content (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    topic_id    INTEGER REFERENCES topics(id),
    team        TEXT NOT NULL DEFAULT 'content',
    content_type TEXT NOT NULL,
    title       TEXT,
    body        TEXT NOT NULL,
    platform    TEXT,
    status      TEXT DEFAULT 'draft' CHECK(status IN (
        'draft','pending_review','approved','rejected','published','failed'
    )),
    model_used  TEXT,
    tokens_used INTEGER DEFAULT 0,
    created_at  TEXT DEFAULT (datetime('now')),
    published_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_content_status ON content(status);

-- ═══ 4. Projects (built by coding team) ═══
CREATE TABLE IF NOT EXISTS projects (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL,
    description TEXT,
    template    TEXT,
    status      TEXT DEFAULT 'pending' CHECK(status IN (
        'pending','building','testing','fix_attempt_1','fix_attempt_2',
        'fix_attempt_3','escalated','complete','failed'
    )),
    repo_url    TEXT,
    local_path  TEXT,
    fix_attempts INTEGER DEFAULT 0,
    model_used  TEXT,
    created_at  TEXT DEFAULT (datetime('now')),
    completed_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);

-- ═══ 5. Outreach (sales team) ═══
CREATE TABLE IF NOT EXISTS outreach (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    target_name TEXT NOT NULL,
    target_type TEXT CHECK(target_type IN (
        'person','community','conference','company','maintainer'
    )),
    channel     TEXT CHECK(channel IN ('email','linkedin','reddit','twitter','other')),
    subject     TEXT,
    message     TEXT NOT NULL,
    status      TEXT DEFAULT 'draft' CHECK(status IN (
        'draft','pending_review','approved','sent','replied','follow_up','closed'
    )),
    response    TEXT,
    created_at  TEXT DEFAULT (datetime('now')),
    sent_at     TEXT,
    follow_up_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_outreach_status ON outreach(status);

-- ═══ 6. CEO Plans ═══
CREATE TABLE IF NOT EXISTS ceo_plans (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    plan_type   TEXT CHECK(plan_type IN ('daily','weekly','ad_hoc')),
    summary     TEXT NOT NULL,
    details     TEXT NOT NULL,
    status      TEXT DEFAULT 'proposed' CHECK(status IN (
        'proposed','approved','modified','rejected','in_progress','completed'
    )),
    human_notes TEXT,
    created_at  TEXT DEFAULT (datetime('now')),
    approved_at TEXT
);

-- ═══ 7. Task Queue (CEO assigns to teams) ═══
CREATE TABLE IF NOT EXISTS tasks (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    plan_id     INTEGER REFERENCES ceo_plans(id),
    team        TEXT NOT NULL CHECK(team IN (
        'content','coding','devops','marketing','sales'
    )),
    description TEXT NOT NULL,
    priority    INTEGER DEFAULT 5 CHECK(priority BETWEEN 1 AND 10),
    status      TEXT DEFAULT 'queued' CHECK(status IN (
        'queued','running','completed','failed','cancelled'
    )),
    result      TEXT,
    model_used  TEXT,
    tokens_used INTEGER DEFAULT 0,
    created_at  TEXT DEFAULT (datetime('now')),
    started_at  TEXT,
    completed_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_team ON tasks(team);

-- ═══ 8. API Usage Tracking ═══
CREATE TABLE IF NOT EXISTS api_usage (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    provider    TEXT NOT NULL CHECK(provider IN ('groq','mistral','google','ollama')),
    model       TEXT NOT NULL,
    team        TEXT,
    tokens_in   INTEGER DEFAULT 0,
    tokens_out  INTEGER DEFAULT 0,
    latency_ms  INTEGER DEFAULT 0,
    success     INTEGER DEFAULT 1,
    error       TEXT,
    created_at  TEXT DEFAULT (datetime('now'))
);

-- ═══ 9. System Health ═══
CREATE TABLE IF NOT EXISTS health_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    component   TEXT NOT NULL,
    status      TEXT NOT NULL CHECK(status IN ('ok','warn','error','down')),
    message     TEXT,
    details     TEXT,
    created_at  TEXT DEFAULT (datetime('now'))
);
"""


class Database:
    """Thread-safe SQLite wrapper for MACH-1."""

    def __init__(self, db_path: Path = DB_PATH):
        self.db_path = db_path
        self._init_db()

    def _init_db(self):
        with self._conn() as conn:
            conn.executescript(SCHEMA)
            log.info(f"Database ready at {self.db_path}")

    @contextmanager
    def _conn(self):
        conn = sqlite3.connect(str(self.db_path), timeout=10)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA foreign_keys=ON")
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    # ── Generic helpers ──────────────────────────────

    def execute(self, sql: str, params: tuple = ()) -> list:
        with self._conn() as conn:
            cursor = conn.execute(sql, params)
            return [dict(row) for row in cursor.fetchall()]

    def execute_one(self, sql: str, params: tuple = ()) -> Optional[dict]:
        rows = self.execute(sql, params)
        return rows[0] if rows else None

    def insert(self, sql: str, params: tuple = ()) -> int:
        with self._conn() as conn:
            cursor = conn.execute(sql, params)
            return cursor.lastrowid

    def update(self, sql: str, params: tuple = ()) -> int:
        with self._conn() as conn:
            cursor = conn.execute(sql, params)
            return cursor.rowcount

    # ── RSS Sources ──────────────────────────────────

    def add_rss_source(self, name: str, url: str, category: str = "general") -> int:
        return self.insert(
            "INSERT OR IGNORE INTO rss_sources (name, url, category) VALUES (?, ?, ?)",
            (name, url, category),
        )

    def get_rss_sources(self, enabled_only: bool = True) -> list:
        sql = "SELECT * FROM rss_sources"
        if enabled_only:
            sql += " WHERE enabled = 1"
        return self.execute(sql)

    # ── Topics ───────────────────────────────────────

    def add_topic(self, title: str, url: str, source_id: int, summary: str = "") -> int:
        return self.insert(
            "INSERT OR IGNORE INTO topics (title, url, source_id, summary) VALUES (?, ?, ?, ?)",
            (title, url, source_id, summary),
        )

    def get_topics(self, status: str = None, limit: int = 50) -> list:
        sql = "SELECT t.*, rs.name as source_name FROM topics t LEFT JOIN rss_sources rs ON t.source_id = rs.id"
        params = ()
        if status:
            sql += " WHERE t.status = ?"
            params = (status,)
        sql += " ORDER BY t.score DESC LIMIT ?"
        params = params + (limit,)
        return self.execute(sql, params)

    def update_topic_status(self, topic_id: int, status: str) -> int:
        return self.update(
            "UPDATE topics SET status = ? WHERE id = ?", (status, topic_id)
        )

    def update_topic_score(self, topic_id: int, score: float) -> int:
        return self.update(
            "UPDATE topics SET score = ?, status = 'ranked' WHERE id = ?",
            (score, topic_id),
        )

    # ── Content ──────────────────────────────────────

    def add_content(self, topic_id: int, content_type: str, title: str,
                    body: str, platform: str = None, model_used: str = None,
                    tokens_used: int = 0, team: str = "content") -> int:
        return self.insert(
            """INSERT INTO content
               (topic_id, team, content_type, title, body, platform, model_used, tokens_used)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (topic_id, team, content_type, title, body, platform, model_used, tokens_used),
        )

    def get_content(self, status: str = None, limit: int = 50) -> list:
        sql = "SELECT * FROM content"
        params = ()
        if status:
            sql += " WHERE status = ?"
            params = (status,)
        sql += " ORDER BY created_at DESC LIMIT ?"
        params = params + (limit,)
        return self.execute(sql, params)

    def update_content_status(self, content_id: int, status: str) -> int:
        return self.update(
            "UPDATE content SET status = ? WHERE id = ?", (status, content_id)
        )

    # ── Projects ─────────────────────────────────────

    def add_project(self, name: str, description: str, template: str,
                    model_used: str = None) -> int:
        return self.insert(
            "INSERT INTO projects (name, description, template, model_used) VALUES (?, ?, ?, ?)",
            (name, description, template, model_used),
        )

    def get_projects(self, status: str = None, limit: int = 50) -> list:
        sql = "SELECT * FROM projects"
        params = ()
        if status:
            sql += " WHERE status = ?"
            params = (status,)
        sql += " ORDER BY created_at DESC LIMIT ?"
        params = params + (limit,)
        return self.execute(sql, params)

    def update_project_status(self, project_id: int, status: str) -> int:
        now = datetime.now(timezone.utc).isoformat() if status == "complete" else None
        if now:
            return self.update(
                "UPDATE projects SET status = ?, completed_at = ? WHERE id = ?",
                (status, now, project_id),
            )
        return self.update(
            "UPDATE projects SET status = ? WHERE id = ?", (status, project_id)
        )

    def increment_fix_attempts(self, project_id: int) -> int:
        return self.update(
            "UPDATE projects SET fix_attempts = fix_attempts + 1 WHERE id = ?",
            (project_id,),
        )

    # ── Outreach ─────────────────────────────────────

    def add_outreach(self, target_name: str, target_type: str, channel: str,
                     subject: str, message: str) -> int:
        return self.insert(
            """INSERT INTO outreach (target_name, target_type, channel, subject, message)
               VALUES (?, ?, ?, ?, ?)""",
            (target_name, target_type, channel, subject, message),
        )

    def get_outreach(self, status: str = None, limit: int = 50) -> list:
        sql = "SELECT * FROM outreach"
        params = ()
        if status:
            sql += " WHERE status = ?"
            params = (status,)
        sql += " ORDER BY created_at DESC LIMIT ?"
        params = params + (limit,)
        return self.execute(sql, params)

    def update_outreach_status(self, outreach_id: int, status: str) -> int:
        return self.update(
            "UPDATE outreach SET status = ? WHERE id = ?", (status, outreach_id)
        )

    # ── CEO Plans ────────────────────────────────────

    def add_plan(self, plan_type: str, summary: str, details: str) -> int:
        return self.insert(
            "INSERT INTO ceo_plans (plan_type, summary, details) VALUES (?, ?, ?)",
            (plan_type, summary, details),
        )

    def get_plans(self, status: str = None, limit: int = 20) -> list:
        sql = "SELECT * FROM ceo_plans"
        params = ()
        if status:
            sql += " WHERE status = ?"
            params = (status,)
        sql += " ORDER BY created_at DESC LIMIT ?"
        params = params + (limit,)
        return self.execute(sql, params)

    def update_plan_status(self, plan_id: int, status: str,
                           human_notes: str = None) -> int:
        if human_notes:
            now = datetime.now(timezone.utc).isoformat()
            return self.update(
                "UPDATE ceo_plans SET status = ?, human_notes = ?, approved_at = ? WHERE id = ?",
                (status, human_notes, now, plan_id),
            )
        return self.update(
            "UPDATE ceo_plans SET status = ? WHERE id = ?", (status, plan_id)
        )

    # ── Tasks ────────────────────────────────────────

    def add_task(self, team: str, description: str, plan_id: int = None,
                 priority: int = 5) -> int:
        return self.insert(
            "INSERT INTO tasks (plan_id, team, description, priority) VALUES (?, ?, ?, ?)",
            (plan_id, team, description, priority),
        )

    def get_tasks(self, team: str = None, status: str = None, limit: int = 50) -> list:
        sql = "SELECT * FROM tasks WHERE 1=1"
        params = []
        if team:
            sql += " AND team = ?"
            params.append(team)
        if status:
            sql += " AND status = ?"
            params.append(status)
        sql += " ORDER BY priority DESC, created_at ASC LIMIT ?"
        params.append(limit)
        return self.execute(sql, tuple(params))

    def update_task(self, task_id: int, status: str, result: str = None,
                    model_used: str = None, tokens_used: int = 0) -> int:
        now = datetime.now(timezone.utc).isoformat()
        if status == "running":
            return self.update(
                "UPDATE tasks SET status = ?, started_at = ? WHERE id = ?",
                (status, now, task_id),
            )
        return self.update(
            """UPDATE tasks SET status = ?, result = ?, model_used = ?,
               tokens_used = ?, completed_at = ? WHERE id = ?""",
            (status, result, model_used, tokens_used, now, task_id),
        )

    # ── API Usage ────────────────────────────────────

    def log_api_call(self, provider: str, model: str, team: str = None,
                     tokens_in: int = 0, tokens_out: int = 0,
                     latency_ms: int = 0, success: bool = True,
                     error: str = None) -> int:
        return self.insert(
            """INSERT INTO api_usage
               (provider, model, team, tokens_in, tokens_out, latency_ms, success, error)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (provider, model, team, tokens_in, tokens_out, latency_ms,
             1 if success else 0, error),
        )

    def get_api_usage_today(self, provider: str = None) -> list:
        sql = """SELECT provider, model, COUNT(*) as calls,
                 SUM(tokens_in) as total_in, SUM(tokens_out) as total_out,
                 AVG(latency_ms) as avg_latency,
                 SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) as errors
                 FROM api_usage
                 WHERE date(created_at) = date('now')"""
        params = ()
        if provider:
            sql += " AND provider = ?"
            params = (provider,)
        sql += " GROUP BY provider, model"
        return self.execute(sql, params)

    # ── Health ───────────────────────────────────────

    def log_health(self, component: str, status: str, message: str = "",
                   details: str = None) -> int:
        return self.insert(
            "INSERT INTO health_log (component, status, message, details) VALUES (?, ?, ?, ?)",
            (component, status, message, details),
        )

    def get_health_latest(self) -> list:
        return self.execute(
            """SELECT h1.* FROM health_log h1
               INNER JOIN (
                   SELECT component, MAX(id) as max_id FROM health_log GROUP BY component
               ) h2 ON h1.id = h2.max_id
               ORDER BY h1.component"""
        )

    # ── Stats ────────────────────────────────────────

    def get_dashboard_stats(self) -> dict:
        """Get all stats needed for the dashboard in one call."""
        stats = {}

        # Content counts by status
        rows = self.execute(
            "SELECT status, COUNT(*) as cnt FROM content GROUP BY status"
        )
        stats["content"] = {r["status"]: r["cnt"] for r in rows}

        # Project counts by status
        rows = self.execute(
            "SELECT status, COUNT(*) as cnt FROM projects GROUP BY status"
        )
        stats["projects"] = {r["status"]: r["cnt"] for r in rows}

        # Outreach counts
        rows = self.execute(
            "SELECT status, COUNT(*) as cnt FROM outreach GROUP BY status"
        )
        stats["outreach"] = {r["status"]: r["cnt"] for r in rows}

        # Today's API usage
        stats["api_today"] = self.get_api_usage_today()

        # Latest health
        stats["health"] = self.get_health_latest()

        # Active plan
        plan = self.execute_one(
            "SELECT * FROM ceo_plans WHERE status IN ('proposed','approved','in_progress') ORDER BY created_at DESC LIMIT 1"
        )
        stats["active_plan"] = plan

        # Pending tasks
        rows = self.execute(
            "SELECT team, COUNT(*) as cnt FROM tasks WHERE status IN ('queued','running') GROUP BY team"
        )
        stats["pending_tasks"] = {r["team"]: r["cnt"] for r in rows}

        # Topic counts
        rows = self.execute(
            "SELECT status, COUNT(*) as cnt FROM topics GROUP BY status"
        )
        stats["topics"] = {r["status"]: r["cnt"] for r in rows}

        return stats


# Singleton
db = Database()
